### ISSUE TITLE
Add Coverage Tests for Shapes Operations

### ISSUE THREAD

**Issue by eholum** [eholum/RegionLibraryTasks#12]
At least the ones of these that are used:

regCopyShape
regInsideShape
regPrintShape

if we're keeping these:
regAppendShape
regCompareShape
regCompareShapeRaw

**Comment by janlyn7** [comment]
Added tests for regCopyShape, regInsideShape, regPrintShape, regAppendShape, regCompareShape.

regCompareShapeRaw is not used outside of the Region library and should be removed from the public API.
