### ISSUE TITLE
Add Coverage Tests for Computation Functions

### ISSUE THREAD

**Issue by eholum** [eholum/RegionLibraryTasks#8]
regArea
regComputePixellatedArea
regExtent
regGetMaxPoints
regGetNoShapes
regGetShapeNo (is this actually useful?)

**Comment by janlyn7** [comment]
Extended tests in test4.c
- Added regArea, regComputePixellatedArea, and regExtent tests for each of the single-shape regions described

- Updated printMask() function to print the region field in the orientation:
lower left coord   == (xpos0, ypos0)
upper right coord  == (xposN, yposN)

**Comment by janlyn7** [comment]
New test file (test5.c) creates a region and appends three shapes - circle, polygon, rectangle.  After each shape append, it queries the region for regGetMaxPoints, regGetNoShapes, regGetShapeNo.

This also tests regAppendShape, regPrintRegion, regCreateEmptyRegion, regCompareShape, regCopyShape, regInvert.

Need to add test for regGetShapeRadii.

**Comment by janlyn7** [comment]
Actually, function regGetShapeRadii is a typo and does not exist.  

Closing this one out.
